baseURL: "https://edwardsfamilycookbook.com"
languageCode: "en-us"
title: "Edwards Family Cookbook"
theme: "gochowdown"

params:
  author: The Edwards
  description: Recipes used by the Edwards family
  keywords: 'recipes'
  # favicon_32: /images/favicon-32x32.png
  # favicon_16: /images/favicon-16x16.png
  footercontent: 'Created by House Waters (2020)'
  hidecredits: true
  hidecopyright: true
  showNavTitle: true
  custom_css: 
    - assets/search.css

menu:
  main:
    - name: Home
      weight: 1
      url: '#'
    - name: Category
      weight: 2
      url: /category/
    # - name: Cuisine
    #   weight: 3
    #   url: /cuisine/
    - name: Tags
      weight: 4
      url: /tags/
taxonomies:
  category: category
  # cusine: cuisine
  tag: tags

outputFormats:
  SearchIndex:
    baseName: search
    mediaType: application/json
outputs:
  home:
  - HTML
  - RSS
  - SearchIndex
